server:
  port: 8082

spring:
  application:
    name: PESSOA-SERVICE
  profiles:
    active: default

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: http://localhost:8761/eureka/
  instance:
    hostname: localhost